"""Build the canonical Start-screen registry from immutable final analyses."""
from __future__ import annotations
import hashlib,json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]/"artifacts"/"launcher-primitives-01"
OUT=Path(__file__).resolve().parents[2]/"research"/"start-screen"/"measurements.json"

def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 plan=json.loads((Path(__file__).with_name("scenarios.json")).read_text())
 by={}
 for q in ROOT.glob("runs/analysis/final-*/*.quality.json"):
  d=json.loads(q.read_text()); by.setdefault(d["trial"].rsplit("_r",1)[0],[]).append((q,d))
 rows=[]
 canonical={"start_rest":"shell-observatory-01","live_tile_passive_flip":"shell-observatory-01","tile_hold_edit":"calendar-confirmation-01","tile_tap_launch":"calendar-confirmation-01","start_to_app_list_drag_commit":"start-app-list-confirmation-01","start_to_app_list_flick":"start-app-list-confirmation-01","start_to_app_list_cancel":"single-drag-cancel-confirmation-01","app_list_to_start_cancel":"single-drag-cancel-confirmation-01","app_list_to_start_drag_commit":"scroll-inverse-confirmation-01","app_list_to_start_flick":"scroll-inverse-confirmation-01","app_list_scroll_slow":"scroll-inverse-confirmation-01","app_list_scroll_flick":"scroll-inverse-confirmation-01","app_list_overscroll":"scroll-inverse-confirmation-01","start_scroll_slow":"scroll-inverse-confirmation-01","start_scroll_flick":"scroll-inverse-confirmation-01","start_overscroll":"scroll-inverse-confirmation-01","app_list_rest":"app-list-confirmation-01","alphabet_grid_open":"app-list-confirmation-01","alphabet_grid_select":"alphabet-select-corrected-01","alphabet_grid_cancel":"alphabet-cancel-corrected-01","app_list_item_launch":"app-list-confirmation-01","app_to_start_home":"calculator-home-confirmation-01"}
 for s in plan["scenarios"]:
  wanted=canonical.get(s["id"]); found=sorted((q,d) for q,d in by.get(s["id"],[]) if not wanted or q.parent.name=="final-"+wanted); trials=[]
  for q,d in found:
   name=d["trial"]; sess=q.parent.name.removeprefix("final-"); raw=ROOT/"runs"/"capture"/sess/name
   quality=d["quality"]
   trials.append({"trial":name,"session":sess,"reset_frame":str((raw/"reset.png").relative_to(ROOT)).replace("\\","/"),"mid_frame":str((raw/"frames"/f"{max(0,quality['frame_count']//2):06d}.png").relative_to(ROOT)).replace("\\","/"),"final_frame":str((raw/"frames"/f"{max(0,quality['frame_count']-1):06d}.png").relative_to(ROOT)).replace("\\","/"),"manifest_sha256":d["manifest_sha256"],"frame_count":quality["frame_count"],"changed_valid_observations":quality["changed_observations"],"max_gap_ms":quality["max_capture_start_gap_ms"],"delivered_events_complete":quality["events_file_present"],"trial_gate_passed":quality["trial_gate_passed"],"exclusions":[]})
  gate=len(trials)==3 and all(t["trial_gate_passed"] for t in trials)
  outcomes={"start_to_app_list_drag_commit":"commit to app list","start_to_app_list_flick":"commit to app list","app_list_to_start_drag_commit":"commit to Start","app_list_to_start_flick":"snap-back/rejected commit","app_list_to_start_flick_commit_strong":"snap-back/rejected commit","start_to_app_list_cancel":"partial displacement then Start snap-back","app_list_to_start_cancel":"partial displacement then app-list snap-back","tile_hold_edit":"edit-entered/exited unchanged","tile_tap_launch":"Calendar launched; Home recovered","app_list_item_launch":"Calculator launched","app_to_start_home":"Home entry to Start","alphabet_grid_open":"grid opened","alphabet_grid_select":"settled alphabet grid b cell selected; B section with Battery Saver, Calculator, Calendar, Camera, and Cortana visible","alphabet_grid_cancel":"grid canceled","reverse-while-held":"unsupported"}
  outcome=outcomes.get(s["id"],"captured observed state")
  cls="rejected" if "rejected" in outcome else ("captured" if trials else "unsupported-or-not-captured")
  supplemental=["pilot/calibration trials excluded from canonical repeat gate"]
  if s["id"]=="app_to_start_home":
   supplemental.append({"session":"app-list-cancel-home-confirmation-01","trials":["app_to_start_home_r01","app_to_start_home_r02","app_to_start_home_r03"],"class":"rejected","reason":"invalid-precondition-app-list","requested_outcome_achieved":False,"observed_outcome":"initial retained frame is app list; this is lateral app-list behavior, not Calculator-to-Start Home entry"})
  if s["id"]=="alphabet_grid_cancel":
   supplemental.append({"session":"app-list-cancel-home-confirmation-01","trials":["alphabet_grid_cancel_r01","alphabet_grid_cancel_r02","alphabet_grid_cancel_r03"],"class":"rejected","reason":"invalid-precondition-unsettled-app-list","requested_outcome_achieved":False,"observed_outcome":"header tap arrived before Start-to-app-list settled; each old trial visibly launched Calculator instead of opening and dismissing the alphabet grid"})
  if s["id"]=="alphabet_grid_select":
   supplemental.append({"session":"app-list-confirmation-01","trials":["alphabet_grid_select_r01","alphabet_grid_select_r02","alphabet_grid_select_r03"],"class":"rejected","reason":"invalid-precondition-and-invalid-terminal","requested_outcome_achieved":False,"observed_outcome":"the header tap was not protected by a settle wait and the x=179 tap was mislabeled as b although it lies in the declared a cell; retained terminal frames do not prove the intended enabled-letter selection"})
  rows.append({"id":s["id"],"requested_intent":s["id"],"requested_outcome_achieved":cls=="captured","observed_outcome":outcome,"class":cls,"repeats":len(trials),"scenario_motion_claim_eligible":gate,"scenario_gate_reason":"three valid trial gates" if gate else "not all three trials pass gate","trials":trials,"supplemental_evidence":supplemental,"limits":["host clocks only","rendered pixels only"]})
 phases=[("start_scroll_slow","scroll-inverse-confirmation-01/start_scroll_slow_r03",[0,23,45]),("start_overscroll","scroll-inverse-confirmation-01/start_overscroll_r03",[0,26,51]),("app_list_scroll_slow","scroll-inverse-confirmation-01/app_list_scroll_slow_r03",[0,40,80]),("app_list_to_start_drag_commit","scroll-inverse-confirmation-01/app_list_to_start_drag_commit_r03",[0,29,58]),("start_to_app_list_drag_commit","start-app-list-confirmation-01/start_to_app_list_drag_commit_r03",[0,27,53]),("start_to_app_list_cancel","single-drag-cancel-confirmation-01/start_to_app_list_cancel_r03",[0,25,46]),("app_list_to_start_cancel","single-drag-cancel-confirmation-01/app_list_to_start_cancel_r03",[0,25,53]),("app_to_start_home","calculator-home-confirmation-01/app_to_start_home_r03",[0,25,49]),("alphabet_grid_open","app-list-confirmation-01/alphabet_grid_open_r03",[0,27,54]),("alphabet_grid_select","alphabet-select-corrected-01/alphabet_grid_select_r03",[0,11,28]),("alphabet_grid_cancel","alphabet-cancel-corrected-01/alphabet_grid_cancel_r03",[0,25,55]),("app_list_item_launch","app-list-confirmation-01/app_list_item_launch_r03",[0,24,47]),("tile_hold_edit","calendar-edit-launch-pilot-01/tile_hold_edit_r01",[0,28,51]),("tile_tap_launch","calendar-edit-launch-pilot-01/tile_tap_launch_r01",[0,15,34]),("live_tile_passive_flip","shell-observatory-01/live_tile_passive_flip_r01",[0,24,32])]
 phase_rows=[{"interaction":i,"frames":[f"runs/capture/{p}/frames/{n:06d}.png" for n in ns],"phase_order":"start→observed transition→end","numeric_observation":{"frame_indices":ns},"limit":"host capture only"} for i,p,ns in phases]
 alphabet_geometry={"frame":"runs/capture/alphabet-select-corrected-01/alphabet_grid_select_r03/reset.png","overlay_bbox":[24,19,456,785],"columns":4,"cell_a_bbox":[135,19,233,117],"cell_b_bbox":[246,19,344,117],"cell_size_px":[99,99],"gutter_px":12,"bbox_convention":"inclusive raster bounds; manually inspected from the settled replacement grid; ±1px","enabled_color":"#3e65ff","disabled_color":"#202020"}
 result={"schema_version":4,"path_semantics":"all frame paths are relative to artifacts/launcher-primitives-01","bbox_convention":"inclusive pixel bounds; manual raster landmarks ±2px","source":{"adapter":"start-screen-wp81-wvga","viewport":[480,800]},"scenario_registry":rows,"geometry":{"start_layout":{"sample_frame":"runs/capture/shell-observatory-01/start_rest_r01/frames/000000.png","large_tile_px":[210,210],"small_tile_px":[99,99],"gutter_px":12,"method":"flat-color connected components","uncertainty_px":1},"tile_icons":[{"name":"Phone","bbox":[100,109,148,181]},{"name":"Messaging","bbox":[277,84,311,110]},{"name":"IE","bbox":[382,82,430,126]},{"name":"Mail","bbox":[278,202,311,228]},{"name":"Calendar","bbox":[107,653,226,700]},{"name":"Kid's Corner","bbox":[308,552,392,657]}],"tile_labels_live_text":[{"text":"Fake GSM Network","bbox":[34,237,195,253]},{"text":"People","bbox":[34,460,87,477]},{"text":"Sun 30","bbox":[116,653,225,700]},{"text":"Kid's Corner","bbox":[256,682,351,699]}],"app_list_layout":{"frame":"runs/capture/app-list-confirmation-01/app_list_rest_r01/reset.png","search_bbox":[25,57,67,98],"header_bbox":[86,57,147,118],"row_pitch_px":74,"calculator_icon_bbox":[86,427,147,488],"calculator_name_bbox":[164,444,298,468],"calculator_baseline_y":468,"icon_name_gap_px":16},"alphabet_grid":{"frame":"runs/capture/app-list-confirmation-01/alphabet_grid_open_r03/frames/000054.png","overlay_bbox":[24,20,456,785],"columns":4,"cell_example_bbox":[123,20,234,118],"gutter_px":11,"enabled_color":"#3e65ff","disabled_color":"#202020"},"edit_mode":{"frame":"runs/capture/calendar-edit-launch-pilot-01/tile_hold_edit_r01/frames/000028.png","calendar_bbox":[24,500,233,709],"annulus_method":"min(rgb)>=180; spread<=15; radius 18..25","unpin":{"bbox":[228,456,272,500],"center":[250,478],"diameter_px":45},"resize":{"bbox":[227,691,273,736],"center":[250,714],"diameter_px":46},"uncertainty_px":2},"motion_phase_samples":phase_rows},"review_tooling_note":"Rapid multi-image preview was inconsistent; PIL/source hashes show complete app-list cancel r03 frames. No raw anomaly/exclusion is recorded.","unknowns":["font family/point size","exact easing","physical latency"]}
 result["geometry"]["alphabet_grid"] = alphabet_geometry
 OUT.write_text(json.dumps(result,indent=2),encoding="utf-8")
if __name__=="__main__": main()
